providers:
  loader:
    provider_id: loader.markdown
  sectioner:
    provider_id: sectioner.markdown_headings
    params:
      max_section_level: 2
      include_heading: true
  chunker:
    provider_id: chunker.rcts_within_section
    params:
      chunk_size: 800
      chunk_overlap: 120
      separators: ["\n\n", "\n", " ", ""]
  embedder:
    provider_id: embedder.fake
    params:
      dim: 8
  llm:
    provider_id: llm.fake
    params:
      name: fake-llm
  vector_index:
    provider_id: vector.chroma_lite
  retriever:
    provider_id: retriever.chroma_dense
    params:
      text_norm_profile_id: default
  sparse_retriever:
    provider_id: sparse_retriever.fts5
  fusion:
    provider_id: fusion.rrf
    params:
      k: 60
  reranker:
    provider_id: reranker.noop
